version: '3'

services:
  mongo-express:
    image: mongo-express
    ports:
      - 8085:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: maddytec
      ME_CONFIG_BASICAUTH_PASSWORD: maddytec@123
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: maddytec@123
    links:
      - mongo
    networks:
      - mongo-compose-network
    restart: always

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: maddytec@123
    ports:
      - "27017:27017"
    volumes:
      - ./data/db
    networks:
      - mongo-compose-network
    restart: always

networks:
  mongo-compose-network:
    driver: bridge